<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetTestVersion)</TargetFramework>
    <RootNamespace>Clasp.QuickStart</RootNamespace>
    <AssemblyName>CLASP.NET.QuickStart</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CLASP.NET\CLASP.NET.csproj" />
  </ItemGroup>

</Project>
